apiVersion: skaffold/v2beta28
kind: Config
build:
  local: {}
  artifacts:
  - image: ec2-api
    docker:
      dockerfile: docker/Dockerfile.local
  # Note: switched to using docker builder above
  # because buildpacks don't support arm64 (breaks on M1)
  # artifacts:
  # - image: ec2-api
  #   buildpacks:
  #     builder: paketobuildpacks/builder:tiny
deploy:
  helm:
    releases:
    - name: ec2api
      artifactOverrides:
        image: ec2-api
      chartPath: k8s/api
      setFiles:
        apiconfig: config/config.json
      setValues:
        probePath: '/v2/ec2/ping'
        ingress.rules[0].paths[0]: '/v2/ec2'
